# Generated by Django 3.2 on 2021-04-29 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timesheet Date')),
                ('approved', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timesheet Date'))),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', help_text='Document code or any other Item ID.', max_length=70)),
                ('reference', models.CharField(help_text='Transmitall number or any other project reference.', max_length=70)),
                ('from_time', models.TimeField(default=django.utils.timezone.now, verbose_name='from')),
                ('to_time', models.TimeField(default=django.utils.timezone.now, verbose_name='to')),
                ('seconds', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('attachments', models.FileField(blank=True, upload_to='')),
                ('note', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.activity')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='timesheet.Tag')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.timesheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['from_time'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('day_hours', models.IntegerField(default=8, help_text='Expected working hours per day.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('I', 'info'), ('A', 'action'), ('!', 'warning')], default='I', max_length=3)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.task')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(related_name='user_activity', to=settings.AUTH_USER_MODEL),
        ),
    ]
